[system]
DATABASE = bin/phreeqc_P.dat
SELFILE = output/Results.sel

[batch]
OXIC= FALSE   # Run R3: Plot oxic batch sorption
ANOXIC= FALSE # Run R4: Plot anoxic batch sorption

[site]
HEHE_BED = FALSE
TUGOU_BANK = FALSE

[validation]
NOEDLER = TRUE # Run R5: Plot Noedler validation data


