name: smx_batch_model
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core Data & Utilities
  - pandas>=1.3.0
  - numpy>=1.21.0
  - configparser>=5.0.0
  
  # Plotting & Visualization
  - matplotlib>=3.4.0
  - plotly>=5.0.0
  - kaleido>=0.2.1
  - seaborn
  
  # Sensitivity Analysis
  - scikit-learn
  
  # Development & Testing
  - pip
  - jupyter
  
  # pip dependencies
  - pip
  - pip:
    - SALib>=1.4.0
    - progressbar2>=3.50.0