[system]
DATABASE = bin/phreeqc_P.dat
SELFILE = output/Results.sel


[batch]
OXIC= FALSE
ANOXIC= TRUE
THREEANTI= FALSE
AMMET= TRUE


[site]
HEHE_BED = FALSE
TUGOU_BANK = FALSE

[validation]
NOEDLER = TRUE
